const express=require('express')
const authorization=require('../middleware/authorization')
const signup=require('../controller/signupController')
const {signin,generateOTP,verifyOTP}=require('../controller/signinController')
const {addSite,home,search,selectedSite,editSite,deleteSite}=require('../controller/sitesController')
const {GetNewAccessToken,logout}=require('../controller/refreshToken')
const router=express.Router()
const resetMPin=require('../controller/passwordController')

router.post('/signup',signup)
router.post('/signin',signin)
router.post('/refreshToken',authorization,GetNewAccessToken)
router.delete('/logout',authorization,logout)
router.delete('/deleteSite',authorization,deleteSite)
// router.post('/forgotPassword',forgotPassword)
router.get('/generateOTP',generateOTP)
router.post('/verifyOTP',verifyOTP)
router.post('/home/addSite',authorization,addSite)
router.post('/home',authorization,home)
router.get('/home',authorization,search)
router.post('/home/selectedSite',authorization,selectedSite)
router.post('/home/selectedSite/editSite',authorization,editSite)
router.get('/sync',authorization,home) // get all the site documents of the user
router.post('/resetMPin',authorization,resetMPin)

module.exports=router 